In [7]:
import numpy as np


In [16]:
#splitting words and vectors seperate

#embedding available here
#https://nlp.stanford.edu/projects/glove/  
#In this tutorial i am using glove.6B.100d.txt

word_list=[]
word_embedding=[]
with open('glove.6B.100d.txt','r') as f:
    for line in f:
        data=line.split()
        word_list.append(data[0])
        word_embedding.append([float(i) for i in data[1:]])


np.save('word_list',word_list)
np.save('word_embedding',word_embedding)
    

In [8]:
#loading word_list 
#loading word_embedding

word_list=np.load('word_list.npy')
word_embedding=np.load('word_embedding.npy')



In [61]:
#data clearning

#converting text to vectors

import re
import sys
import unicodedata

data = [
    """WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.""",
    """This isn't the comedic Robin Williams, nor is it the quirky/insane Robin Williams of recent thriller fame. This is a hybrid of the classic drama without over-dramatization, mixed with Robin's new love of the thriller. But this isn't a thriller, per se. This is more a mystery/suspense vehicle through which Williams attempts to locate a sick boy and his keeper.<br /><br />Also starring Sandra Oh and Rory Culkin, this Suspense Drama plays pretty much like a news report, until William's character gets close to achieving his goal.<br /><br />I must say that I was highly entertained, though this movie fails to teach, guide, inspect, or amuse. It felt more like I was watching a guy (Williams), as he was actually performing the actions, from a third person perspective. In other words, it felt real, and I was able to subscribe to the premise of the story.<br /><br />All in all, it's worth a watch, though it's definitely not Friday/Saturday night fare.<br /><br />It rates a 7.7/10 from...<br /><br />the Fiend :."""]

final_ = []



def get_final(data_line):
    sub_final = []
    fg = " ".join(re.split(r'\/|-', data_line))
    data_line=fg.replace('<br  >', ' ')


    d = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))

    new = data_line.translate(d).split()
    print(new)
    for i in new:
        try:
            sub_final.append(np.array(word_list).tolist().index(i.lower()))
        except ValueError:
            sub_final.append(399999)
    final_.append(sub_final)


for ii in data:
    get_final(ii)

print(final_)



['WARNING', 'The', 'notebook', 'server', 'is', 'listening', 'on', 'all', 'IP', 'addresses', 'and', 'not', 'using', 'encryption', 'This', 'is', 'not', 'recommended']
['This', 'isnt', 'the', 'comedic', 'Robin', 'Williams', 'nor', 'is', 'it', 'the', 'quirky', 'insane', 'Robin', 'Williams', 'of', 'recent', 'thriller', 'fame', 'This', 'is', 'a', 'hybrid', 'of', 'the', 'classic', 'drama', 'without', 'over', 'dramatization', 'mixed', 'with', 'Robins', 'new', 'love', 'of', 'the', 'thriller', 'But', 'this', 'isnt', 'a', 'thriller', 'per', 'se', 'This', 'is', 'more', 'a', 'mystery', 'suspense', 'vehicle', 'through', 'which', 'Williams', 'attempts', 'to', 'locate', 'a', 'sick', 'boy', 'and', 'his', 'keeper', 'Also', 'starring', 'Sandra', 'Oh', 'and', 'Rory', 'Culkin', 'this', 'Suspense', 'Drama', 'plays', 'pretty', 'much', 'like', 'a', 'news', 'report', 'until', 'Williams', 'character', 'gets', 'close', 'to', 'achieving', 'his', 'goal', 'I', 'must', 'say', 'that', 'I', 'was', 'highly', 'entertain

In [66]:
import tensorflow as tf

tf.reset_default_graph()

input_x=tf.placeholder(tf.int32,shape=[None,None])

Word_embedding = tf.get_variable(name="W", shape=[400000,100], initializer=tf.constant_initializer(np.array(word_embedding)), trainable=False)
embedding_loopup= tf.nn.embedding_lookup(Word_embedding,input_x)

with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        for ii in final_:
            print(sess.run(embedding_loopup,feed_dict={input_x:[ii]}))
        

    



[[[-0.2989   -0.60051   0.48185  ...  0.095815  0.10687   0.025202]
  [-0.038194 -0.24487   0.72812  ... -0.1459    0.8278    0.27062 ]
  [-0.43801   0.49572   1.1181   ... -0.43953   1.2514    0.070576]
  ...
  [-0.54264   0.41476   1.0322   ... -1.2969    0.76217   0.46349 ]
  [-0.19104   0.17601   0.3692   ... -0.5968    0.080843  0.27866 ]
  [-0.38725  -0.38811  -0.49279  ... -0.099383  0.18399  -0.083023]]]
[[[-0.57058   0.44183   0.70102  ... -0.66102   0.47197   0.37253 ]
  [-0.097035  0.23205  -0.010545 ... -0.084817 -0.45299   0.31053 ]
  [-0.038194 -0.24487   0.72812  ... -0.1459    0.8278    0.27062 ]
  ...
  [ 0.30731   0.24737   0.68231  ...  0.13735   1.0103   -0.77614 ]
  [-0.038194 -0.24487   0.72812  ... -0.1459    0.8278    0.27062 ]
  [ 0.15544  -0.25449   0.7368   ... -0.25619   0.36918  -0.55068 ]]]


In [65]:

#validating result by manual embedding lookup

print(word_embedding[1975])

[-0.2989    -0.60051    0.48185   -0.13038   -0.068388   0.16441
 -0.34119   -0.52143   -0.025612   0.087871  -0.034554  -0.26052
 -0.1239     0.10174    0.54033    0.26336   -0.29377   -0.37216
 -0.33782   -0.28566    0.0096186 -0.20075   -0.1592     0.027219
 -0.20424    0.59778   -0.48239    0.90715   -0.36636   -0.1993
  0.84447   -0.15136   -0.097391   0.78983   -0.34897    0.028516
  0.045391  -0.39529    0.33923    0.04998   -1.1097     0.22696
  0.13564   -0.18441    0.78137   -0.22849    0.4151     0.13281
 -0.19269   -0.96898    0.9596     0.36388   -0.12575    0.81254
  0.13076   -1.892      0.33793   -0.15247    1.8207     0.18241
  0.027438   0.3785    -0.25259   -0.12538   -0.074345   0.2165
 -0.831      0.31736    0.37616   -0.27634   -0.42189   -0.28225
 -0.11396   -0.80373    0.45635    0.82757    0.70023    0.49755
 -0.64901   -0.24195    1.0454    -1.4573    -0.97332   -0.051946
 -1.2024    -0.4798     0.33814    0.24562    0.27226   -0.17699
  0.053299   0.39419   -